# Generated by Django 4.1.6 on 2023-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата дедлайна'),
        ),
    ]
