# Generated by Django 4.1.6 on 2023-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_todo_completion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_at',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата дедлайна'),
        ),
    ]
