# Generated by Django 4.1.6 on 2023-02-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_todo_completion_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
