# Generated by Django 4.1.6 on 2023-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0004_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Опишите задачу', max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=200, verbose_name='Статус')),
                ('completion_at', models.CharField(max_length=50, null=True, verbose_name='Дата дедлайна')),
            ],
        ),
    ]
