# Generated by Django 4.1.6 on 2023-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='detailed_description',
            field=models.TextField(max_length=3000, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(help_text='Опишите задачу', max_length=300, verbose_name='Описание'),
        ),
    ]
